In [1]:
 a = (1,3)

In [12]:
from collections import deque


In [7]:
a.add((3,1))

In [17]:
def temp(a,b):
    return a+b

In [18]:
kobe = [[1,3]]

In [21]:
temp(*kobe[0])

4

In [3]:
n_diff

2

In [ ]:
[0,0,0,0 ]

In [33]:
temp = set([(0,0,0,0)])

In [35]:
temp = set([(0,0,0,0)])
tuple([0,0,0,0]) in temp

True

In [27]:
a = [3,5,2]
b = a.copy()

In [22]:
a = "0202"

In [26]:
[int(float(x)) for x in list(a)]

[0, 2, 0, 2]

In [8]:
blue, red = 0, 1
seen = set([(0, blue), (0, red)])

In [20]:
set([1])

{1}

In [10]:
ls = [1,2]

In [14]:
from collections import deque

In [15]:
temp = deque([ls])

In [17]:
temp.popleft()

[1, 2]

In [ ]:
row, col = 0, 2
m = 3
n= 3

In [ ]:
 (row, col) !=  (entrance_row, entrance_col) and (row == (m-1) or col == (n-1))

## Resources
[Python-cheat-sheet](https://leetcode.com/discuss/study-guide/2122306/python-cheat-sheet-for-leetcode)

## Get the maximum key or value from dictionary

In [20]:
10*15*4*31*6*7*2

1562400

In [1]:
import numpy as np

In [19]:
np.arange(0.4, 1.1, 0.1)

array([0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [18]:
np.linspace(0.5, 1, 6)

array([0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [12]:
np.linspace(0.5,1, ste)

array([0.5       , 0.5122449 , 0.5244898 , 0.53673469, 0.54897959,
       0.56122449, 0.57346939, 0.58571429, 0.59795918, 0.61020408,
       0.62244898, 0.63469388, 0.64693878, 0.65918367, 0.67142857,
       0.68367347, 0.69591837, 0.70816327, 0.72040816, 0.73265306,
       0.74489796, 0.75714286, 0.76938776, 0.78163265, 0.79387755,
       0.80612245, 0.81836735, 0.83061224, 0.84285714, 0.85510204,
       0.86734694, 0.87959184, 0.89183673, 0.90408163, 0.91632653,
       0.92857143, 0.94081633, 0.95306122, 0.96530612, 0.97755102,
       0.98979592, 1.00204082, 1.01428571, 1.02653061, 1.03877551,
       1.05102041, 1.06326531, 1.0755102 , 1.0877551 , 1.1       ])

In [1]:
a_dictionary = {"a": 1, "b": 2, "c": 0}
b_dictionary = {"d": 1, "e": 2, "f": 0}

In [2]:
a_dictionary.update(b_dictionary)

In [5]:
a2_dict = {"a":1000}
a_dictionary.update(a2_dict)
a_dictionary

{'a': 1000, 'b': 2, 'c': 0, 'd': 1, 'e': 2, 'f': 0}

#### max elements

In [34]:
max(a_dictionary.keys(), key=a_dictionary.get)

'b'

In [28]:
max(a_dictionary, key=a_dictionary.get)

'b'

In [33]:
sorted(a_dictionary, key=a_dictionary.get)[-1]

'b'

In [36]:
sorted(a_dictionary, key=a_dictionary.get, reverse = True)[0]

'b'

#### max values

In [35]:
all_values = a_dictionary.values()
max(all_values)

2

__Sort dictionary with lexicographical order and descending counts__

In [26]:
count_dict = {"x":3,"y":4,"z":5,"a":4}

dict(sorted(count_dict.items(), key = lambda x: (-x[1],x[0]))).keys()

dict_keys(['z', 'a', 'y', 'x'])

__sort on both element ascending__

In [23]:
temp = [[5,6],[5,5],[2,10],[2,11]]

In [17]:
temp.sort()
temp

[[2, 10], [2, 11], [5, 5], [5, 6]]

__only sort the first element__

In [2]:
temp = [[5,6],[5,5],[2,10],[2,11]]
sorted(temp, key = lambda x:(x[0]))

[[2, 10], [2, 11], [5, 6], [5, 5]]

__sort on both (same as `.sort()`)__

In [21]:
sorted(temp, key = lambda x:(x[0],x[1])) 

[[2, 10], [2, 11], [5, 5], [5, 6]]

__sort on first ascending and second descending__

In [22]:
sorted(temp, key = lambda x:(x[0],-x[1])) 

[[2, 11], [2, 10], [5, 6], [5, 5]]

In [30]:
temp2 = {1:None}

In [17]:
1 in temp2

True

In [13]:
a = [3,5,1]
sorted(a)

[1, 3, 5]

In [11]:
sorted(a)

[1, 3, 5]

In [14]:
a.pop(0)
a

[5, 1]

In [41]:
intervals =  [[0,30],[5,10],[15,20]]
intervals = sorted(intervals,key = lambda x: (x[0],x[1]))
i = 0
intervals

[[0, 30], [5, 10], [15, 20]]

In [40]:
if (intervals[i][1]>intervals[i+1][0]) or (intervals[i][0] == intervals[i+1][0]):
    print("false") 

false


In [43]:
len(intervals)

3

In [25]:
temp = [[5,6],[5,5],[2,10],[2,11]]
temp.pop()
temp

[[5, 6], [5, 5], [2, 10]]

In [27]:
temp = [[5,6],[5,5],[2,10],[2,11]]
temp.pop(0)
temp

[[5, 5], [2, 10], [2, 11]]

In [30]:
temp = [[5,6],[5,5],[2,10],[2,11]]
for i in range(len(temp)-1):
    temp.pop(0)

In [31]:
temp

[[2, 11]]

In [33]:
temp2 = temp[-1]

In [34]:
temp2[0] = 10000
temp

[[10000, 11]]

## `dictionary.get()`

In [21]:
a = {'x':3,'y':100}

In [22]:
a.get('x')

3

__`.get()` won't raise error__

In [23]:
a.get('z')

In [24]:
a['z']

KeyError: 'z'

## List insert

In [7]:
a = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
a[5:5] = range(10, 13)
a

[0, 1, 2, 3, 4, 10, 11, 12, 5, 6, 7, 8, 9]

In [8]:
a.insert(0,1000)
a

[1000, 0, 1, 2, 3, 4, 10, 11, 12, 5, 6, 7, 8, 9]

## `collections` count 

In [7]:
import collections

In [8]:
def majorityElement(nums):
    counts = collections.Counter(nums)
    return max(counts.keys(), key=counts.get)

In [9]:
majorityElement([1,3,3,3,5])

3

In [10]:
temp = collections.Counter([1,3,3,3,5])

In [1]:
import numpy as np

In [2]:
list(range(1,2))

[1]

#### list of lists

In [4]:
for i, j in [[3,5],[2,4]]:
    print(i,j)

3 5
2 4


### create heterogeneous lists

But this flexibility comes at a cost: to allow these flexible types, each item in the list must contain its own type info, reference count, and other information–that is, each item is a complete Python object. In the special case that all variables are of the same type, much of this information is redundant: it can be much more efficient to store data in a fixed-type array. 

In [2]:
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

### fixed type

In [6]:
x = np.array([range(i, i + 3) for i in [2, 4, 6]])
x

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

### numpy confusing functions

difference between `np.arrange` and `np.linspace`

In [9]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
np.linspace(0,18,10)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18.])

### numpy distributions

In [20]:
## uniform (a,b)
a = 3
b = 5
out = np.random.random(100) * (b-a) + a
np.quantile(out,[0,0.5,1])

array([3.00076968, 4.0011984 , 4.94693757])

In [33]:
## normal (mean, sd)
np.random.normal(loc = 0,scale=1,size=10)
np.random.normal(loc = 0,scale=1,size=(2,5))

array([[ 1.31970288, -0.3063791 , -2.06636449, -0.3009498 , -0.58731355],
       [-1.65031391, -1.11686232,  0.36602873, -0.98115691, -1.52107592]])

In [30]:
## multinomial like sample in R
np.random.choice(np.array(['a','b']),size=5,replace=True,p=[0.1,0.9])

array(['a', 'b', 'a', 'b', 'b'], dtype='<U1')

In [34]:
## sample random intergers from discrete 0 to 9
np.random.randint(0, 10, (3, 3))

9

### dictionary

In [4]:
hashmap = {}
hashmap[35] = 1
hashmap[26] = 2

In [5]:
hashmap

{35: 1, 26: 2}

In [6]:
35 in hashmap

True

In [10]:
[hashmap[35], hashmap[26]]

[1, 2]

In [12]:
min(hashmap[35], hashmap[26])

1

In [18]:
list(reversed(range(5)))

[4, 3, 2, 1, 0]

### heap
To access the smallest item without popping it, use `heap[0]`.

In [13]:
# Python code to demonstrate working of 
# heapify(), heappush() and heappop()
  
# importing "heapq" to implement heap queue
import heapq
  
# initializing list
li = [5, 7, 9, 1, 3]
  
# using heapify to convert list into heap
heapq.heapify(li)
  
# printing created heap
print ("The created heap is : ",end="")
print (list(li))
  
# using heappush() to push elements into heap
# pushes 4
heapq.heappush(li,4)
  
# printing modified heap
print ("The modified heap after push is : ",end="")
print (list(li))
  
# using heappop() to pop smallest element
print ("The popped and smallest element is : ",end="")
print (heapq.heappop(li))

The created heap is : [1, 3, 9, 7, 5]
The modified heap after push is : [1, 3, 4, 7, 5, 9]
The popped and smallest element is : 1


In [3]:
for i, j in [[3,5],[2,4]]:
    print(i,j)

3 5
2 4


## Parsing numbers from text

In [6]:
txt = "h3110 23 cat 444.4 rabbit 11 2 dog"
[s for s in txt.split(" ") if s.isnumeric()]
#[23, 11, 2]

['23', '11', '2']

In [25]:
l = []
for t in txt.split():
    try:
        l.append(float(t))
    except ValueError:
        pass

## List Index

In [19]:
temp = [3,5,10,"kobe",5]

In [20]:
temp.index('kobe')

3

In [22]:
temp.index(5) ## find the index of first 5

1

In [24]:
temp.index(5,2) ##find 5 from index 2 to last

4

In [23]:
[i for i, x in enumerate(temp) if x == 5] 

[1, 4]

## List of list looping


In [1]:
temp = [[2,3],[5,10],[2,10]]
for i,j in temp:
    print(i,j)

2 3
5 10
2 10


## string operation `split` and `strip`

In [24]:
txt = "a \tb\tc\td\te"
things = txt.split("\t")
[x.strip(" ") for x in things]

['a', 'b', 'c', 'd', 'e']

## `copy` and `deepcopy`

In [16]:
import copy

In [17]:
temp = [3,2,[2,5]]
temp2 = temp.copy()
temp2[2][0]=1000
temp

[3, 2, [1000, 5]]

In [18]:
import copy
temp = [3,2,[2,5]]
temp2 = copy.copy(temp)
temp2[2][0]=1000
temp

[3, 2, [1000, 5]]

In [19]:
import copy
temp = [3,2,[2,5]]
temp2 = copy.deepcopy(temp)
temp2[2][0]=1000
temp

[3, 2, [2, 5]]

In [4]:
str(234)

'234'

### check whether a value (string or non-string) is `int` or `float`

`isinstance` work for both negative and postive

In [4]:
isinstance(1, int)

True

In [5]:
isinstance(-1, int)

True

In [2]:
isinstance("1", float)

False

In [7]:
isinstance(1.0, float)

True

In [15]:
"as".isnumeric()

False

`is_digit` works for non-negative number

In [20]:
"-3".isdigit()

False

In [8]:
"3".isdigit()

True

In [11]:
"0".isdigit()

True

## sort list of string by length

In [2]:
x = ["flower","flow","flight"]
sorted(x,key = lambda x: len(x))

['flow', 'flower', 'flight']

In [ ]:
for t in txt.split():
    try:
        l.append(float(t))
    except ValueError:
        pass

In [10]:
temp = ['5 min','-5 asdf','asdf','0 asdf']

In [11]:
out = []
for i in range(len(temp)):
    for j in temp[i].split():
        try:
            out.append(float(j))
        except ValueError:
            pass

In [12]:
out

[5.0, -5.0, 0.0]

### The `isalnum()` method returns True if all characters in the string are alphanumeric (either alphabets or numbers).

In [2]:
name1 = "Python3"
name1.isalnum()

True

In [4]:
"asdf :".isalnum()

False

In [5]:
":".isalnum()

False

In [6]:
if ":".isalnum():
    print('kobe')
else:
    print('bryant')

bryant


In [9]:
name1.lower()

'python3'

## `zip` transpose
`zip(*a)` is equal to `zip(a[0], a[1], a[2])`.

In [ ]:
mat = [[0,0,1,0],[0,0,0,0],[0,0,0,0],[0,1,0,0]]

In [26]:
np.array(mat_t)

array([[0, 0, 0, 0],
       [0, 0, 0, 1],
       [1, 0, 0, 0],
       [0, 0, 0, 0]])

In [38]:
list(zip(*mat))

[(0, 0, 0, 0), (0, 0, 0, 1), (1, 0, 0, 0), (0, 0, 0, 0)]

## `pop` also works as below

In [1]:
temp = [3,2,5]
temp2 = [3,2,5]
temp2[temp.pop(1)]

5

# LC Course

## Recursive

Computability theory proves that any iterative algorithm can be written recursively.

In [5]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [6]:
def print_stuff(i):
    print(i)
    if i<9:
        print_stuff(i+1) 

In [8]:
def print_stuff(i):
    if i>=10:
        return 
    print(i)
    print_stuff(i+1) 

In [9]:
print_stuff(0)

0
1
2
3
4
5
6
7
8
9


In [24]:
def fn(i):
    if i > 3:
        return

    print(i)
    fn(i + 1)
    print(f"End of call where i = {i}")
    return ## same with or without `return`

With recursion, it can get confusing because calls can cascade on top of each other. __The print text is executed in reverse order.__

this is the important part: how recursion "moves" back "up". `fn(4)` triggers the base case, which returns. We are now back in the function call where `i = 3` and the `fn(i + 1)` line has finished, so we move to the next line which prints "End of call where `i = 3`". Once that line runs, we move to the next line, which is a return. Now, we are back in the function call where `i = 2` and the `fn(i + 1)` line has finished, so again we move to the next line and print "End of the call where `i = 2`". This repeats until the original function call to `fn(1)` returns.

In [25]:
fn(1)

1
2
3
End of call where i = 3
End of call where i = 2
End of call where i = 1


## strings

Python strings are not immutable

### O(n) string building
We mentioned earlier that in most languages, strings are immutable. This means concatenating a single character to a string is an $O(n)$ operation. If you have a string that is 1 million characters long, and you want to add one more character, all 1 million characters need to be copied over to another string.

Many problems will ask you to return a string, and usually, this string will be built during the algorithm. Simple concatenation will result in an $O(n^2)$
time complexity for Python.

- Declare a list
- When building the string, add the characters to the list. This is $O(1)$ per operation.
- Once finished, convert the list to a string using `"".join(list)`. This is $O(n)$.

In [26]:
temp = 'asdf'

In [28]:
temp[0] = "d"

TypeError: 'str' object does not support item assignment

In [1]:
def build_string(s):
    arr = []
    for c in s:
        arr.append(c)

    return "".join(arr)

## Array 

Appending to the end of a list is [amortized](https://stackoverflow.com/questions/33044883/why-is-the-time-complexity-of-pythons-list-append-method-o1) O(1).

![title](https://leetcode.com/explore/interview/card/leetcodes-interview-crash-course-data-structures-and-algorithms/703/arraystrings/Figures/DSA/Chapter_1/1_1.png)

### Review `more common patterns`

- `car pooling` and `Brightest Position on Street` "

- difference between subarray and subsequence

## Linked lists

The main advantage of a linked list is that you can add and remove elements at any position in `O(1)`. The caveat is that you need to have a reference to a node at the position in which you want to perform the addition/removal, otherwise the operation is `O(n)`. However, this is still much better than a normal (dynamic) array, which requires `O(n)` for adding and removing from an arbitrary position.

The main disadvantage of a linked list is that there is no random access. If you have a large linked list and want to access the `150,000th` element, then there usually isn't a better way than to start at the head and iterate 150,000 times. So while an array has `O(1)` indexing, a linked list has `O(n)`.

linked lists have the advantage of not having fixed sizes. While dynamic arrays can be resized, under the hood they still are allocated a fixed size - it's just that when this size is exceeded, the array is resized, which is expensive. Linked lists don't suffer from this. However, linked lists have more overhead than arrays - every element needs to have extra storage for the pointers. If you are only storing small items like booleans or characters, then you may be more than doubling the space needed.

When it comes to linked list problems, many solutions are difficult to reach because of their elegance. In many cases, you could simply iterate through the linked list and put all the elements in an array, then just solve the problem using the array. However, the point of these problems is usually to manipulate pointers in a clean way using `O(1)` space

In [63]:
class ListNode:
    def __init__(self, val):
        self.val = val
        self.next = None
    
one = ListNode(1)
two = ListNode(2)
three = ListNode(3)
one.next = two
two.next = three
head = one

### travesal through a linked list

In [64]:
# def get_sum(head):
#     ans = 0
#     while head:
#         ans += head.val
#         head = head.next
    
#     return ans
## better version than above so head is still head
def get_sum(head):
    ans = 0
    dummy = head
    while dummy:
        ans += dummy.val
        dummy = dummy.next
    
    # same as before, but we still have a pointer at the head
    return ans
def print_val(head):
    while head:
        print(head.val)
        head = head.next
        
def print_val_rev(end):
    while end:
        print(end.val)
        end = end.prev        

In [65]:
get_sum(head)

6

### singly linked list

#### add elements to linked list

Note: it is unusual that you will have a pointer to the node at the position before where you want to perform an operation, but we are writing these functions as a demonstration. In most cases, you will need to iterate from the `head` until you are at the desired position.

In [66]:
# Let prev_node be the node at position i - 1
def add_node(prev_node, node_to_add):
    node_to_add.next = prev_node.next
    prev_node.next = node_to_add

In [67]:
two_half = ListNode(8)

In [56]:
add_node(one,two_half)

In [57]:
print_val(one)

1
8
2
3


#### delete node

As mentioned before, when you have a reference to the node at i - 1, then insertion and deletion is `O(1)`. However, without that reference, you need to obtain the reference by iterating from the head, which for an arbitrary position is `O(n)`.

In [58]:
# Let prev_node be the node at position i - 1, delete i th position
def delete_node(prev_node):
    prev_node.next = prev_node.next.next

In [59]:
delete_node(two_half)

In [61]:
print_val(one)

1
8
3


In [62]:
print_val(head)

1
8
3


##### manual deletion

__important__

check `Middle of the Linked List`, 

this is like list of list and data frame operation (see copy and deep copy above)

In [71]:
b = [1,[3,2],5]
a = b
a[0] = 1000
b

[1000, [3, 2], 5]

In [75]:
import pandas as pd

df = pd.DataFrame({"x":[1,2,3], "y":[2,4,5]})
df2 = df
df2['x'] = [1000,20,3]
df

x  y
0  1000  2
1    20  4
2     3  5

In [41]:
class ListNode:
    def __init__(self, val):
        self.val = val
        self.next = None
    
one = ListNode(1)
two = ListNode(2)
three = ListNode(3)
one.next = two
two.next = three
head = one

In [42]:
print_val(one)

1
2
3


In [76]:
## deleting a node
head.next = head.next.next

In [77]:
print_val(one)

1
3


In [37]:
class ListNode:
    def __init__(self, val):
        self.val = val
        self.next = None
    
one = ListNode(1)
two = ListNode(2)
three = ListNode(3)
one.next = two
two.next = three
head = one

In [38]:
head = head.next

In [39]:
print_val(one)

1
2
3


In [40]:
print_val(head)

2
3


### Doubly linked list

In [1]:
class ListNode:
    def __init__(self, val):
        self.val = val
        self.next = None
        self.prev = None

# Let node be the node at position i
def add_node(node, node_to_add):
    prev_node = node.prev
    node_to_add.next = node
    node_to_add.prev = prev_node
    prev_node.next = node_to_add
    node.prev = node_to_add
    
def add_node2(node, node_to_add):
    prev_node = node.prev
    node_to_add.prev = prev_node
    node_to_add.next = node
    node.prev = node_to_add
    prev_node.next = node_to_add
# Let node be the node at position i
def delete_node(node):
    prev_node = node.prev
    next_node = node.next
    prev_node.next = next_node
    next_node.prev = prev_node

In [2]:
one = ListNode(1)
two = ListNode(2)
three = ListNode(3)
kobe = ListNode(8)
one.next = two
two.prev = one
two.next = three
three.prev = two

In [3]:
print_val(one)

NameError: name 'print_val' is not defined

In [46]:
print_val_rev(three)

3
2
1


In [47]:
#add_node(two,kobe)
add_node2(two,kobe)

In [48]:
print_val(one)

1
8
2
3


In [37]:
print_val_rev(three)

3
2
8
1


### Linked lists with sentinel nodes

The previous code we looked at is prone to errors. For example, if we are trying to delete the last node in list, then `nextNode` will be `null`, and trying to access `nextNode.next` would result in an error. With sentinel nodes, we don't need to worry about this scenario because the last node's next points to the sentinel tail.

In [49]:
class ListNode:
    def __init__(self, val):
        self.val = val
        self.next = None
        self.prev = None

def add_to_end(node_to_add):
    node_to_add.next = tail
    node_to_add.prev = tail.prev
    tail.prev.next = node_to_add
    tail.prev = node_to_add

def remove_from_end():
    if head.next == tail:
        return

    node_to_remove = tail.prev
    node_to_remove.prev.next = tail
    tail.prev = node_to_remove.prev

def add_to_start(node_to_add):
    node_to_add.prev = head
    node_to_add.next = head.next
    head.next.prev = node_to_add
    head.next = node_to_add

def remove_from_start():
    if head.next == tail:
        return
    
    node_to_remove = head.next
    node_to_remove.next.prev = head
    head.next = node_to_remove.next

head = ListNode(None)
tail = ListNode(None)
head.next = tail
tail.prev = head

In [20]:
def return_kth(head, k):
    fast = slow = head
    
    for _ in range(k):
        fast = fast.next
    
    while fast:
        slow = slow.next
        fast = fast.next
        
    return slow.val

In [14]:
class ListNode:
    def __init__(self, val):
        self.val = val
        self.next = None
    
one = ListNode(1)
two = ListNode(2)
three = ListNode(3)
four = ListNode(4)
five = ListNode(5)

In [15]:
one.next = two
two.next = three
three.next = four
four.next = five

In [21]:
return_kth(one,k = 2)

None


4

In [3]:
temp = [1,2]
temp2=temp.copy()

In [4]:
temp[0]=100
temp2

[1, 2]

In [5]:
temp

[100, 2]

In [6]:
temp

[100, 2]

In [7]:
temp.insert(1,100)

In [9]:
[0]*5

[0, 0, 0, 0, 0]

In [11]:
list(range(-1, 5, -1))

[]

In [13]:
list(range(5,-1,-1))

[5, 4, 3, 2, 1, 0]

In [1]:
edges = [[0, 1], [1, 2], [2, 0], [2, 3]]

In [6]:
from collections import defaultdict

def build_graph(edges):
    graph = defaultdict(list)
    for x, y in edges:
        graph[x].append(y)
        graph[y].append(x)
        #uncomment the above line if the graph is undirected
    
    return graph

In [7]:
kobe = build_graph(edges)

In [8]:
kobe

defaultdict(list, {0: [1, 2], 1: [0, 2], 2: [1, 0, 3], 3: [2]})

In [10]:
3 in temp

True

In [11]:
3 in [3,5]

True

In [16]:
temp = set(((1,3),(2,4)))

In [18]:
(1,3) in temp

True

In [20]:
set([0])

{0}

In [21]:
rooms = [[1,3],[3,0,1],[2],[0]]
set(rooms[0])

{1, 3}

In [27]:
from collections import deque, defaultdict

rooms_que = deque(rooms)

In [24]:
rooms_que.popleft()

[1, 3]

In [25]:
rooms_que

deque([[3, 0, 1], [2], [0]])

In [26]:
temp = []
if temp:
    print('kobe')

In [28]:
temp = defaultdict(list)

In [29]:
3 in temp

False

In [1]:
temp = {'x':3,'y':5}

In [3]:
for key in temp:
    print(key)

x
y


In [4]:
a = 1
if a:
    print(8)

8
