## Get the maximum key or value from dictionary

In [28]:
a_dictionary = {"a": 1, "b": 2, "c": 0}

#### max elements

In [34]:
max(a_dictionary.keys(), key=a_dictionary.get)

'b'

In [28]:
max(a_dictionary, key=a_dictionary.get)

'b'

In [33]:
sorted(a_dictionary, key=a_dictionary.get)[-1]

'b'

In [36]:
sorted(a_dictionary, key=a_dictionary.get, reverse = True)[0]

'b'

#### max values

In [35]:
all_values = a_dictionary.values()
max(all_values)

2

__Sort dictionary with lexicographical order and descending counts__

In [26]:
count_dict = {"x":3,"y":4,"z":5,"a":4}

dict(sorted(count_dict.items(), key = lambda x: (-x[1],x[0]))).keys()

dict_keys(['z', 'a', 'y', 'x'])

__sort on both element ascending__

In [23]:
temp = [[5,6],[5,5],[2,10],[2,11]]

In [17]:
temp.sort()
temp

[[2, 10], [2, 11], [5, 5], [5, 6]]

__only sort the first element__

In [20]:
temp = [[5,6],[5,5],[2,10],[2,11]]
sorted(temp, key = lambda x:(x[0]))

[[2, 10], [2, 11], [5, 6], [5, 5]]

__sort on both (same as `.sort()`)__

In [21]:
sorted(temp, key = lambda x:(x[0],x[1])) 

[[2, 10], [2, 11], [5, 5], [5, 6]]

__sort on first ascending and second descending__

In [22]:
sorted(temp, key = lambda x:(x[0],-x[1])) 

[[2, 11], [2, 10], [5, 6], [5, 5]]

In [30]:
temp2 = {1:None}

In [17]:
1 in temp2

True

In [13]:
a = [3,5,1]
sorted(a)

[1, 3, 5]

In [11]:
sorted(a)

[1, 3, 5]

In [14]:
a.pop(0)
a

[5, 1]

In [41]:
intervals =  [[0,30],[5,10],[15,20]]
intervals = sorted(intervals,key = lambda x: (x[0],x[1]))
i = 0
intervals

[[0, 30], [5, 10], [15, 20]]

In [40]:
if (intervals[i][1]>intervals[i+1][0]) or (intervals[i][0] == intervals[i+1][0]):
    print("false") 

false


In [43]:
len(intervals)

3

In [25]:
temp = [[5,6],[5,5],[2,10],[2,11]]
temp.pop()
temp

[[5, 6], [5, 5], [2, 10]]

In [27]:
temp = [[5,6],[5,5],[2,10],[2,11]]
temp.pop(0)
temp

[[5, 5], [2, 10], [2, 11]]

In [30]:
temp = [[5,6],[5,5],[2,10],[2,11]]
for i in range(len(temp)-1):
    temp.pop(0)

In [31]:
temp

[[2, 11]]

In [33]:
temp2 = temp[-1]

In [34]:
temp2[0] = 10000
temp

[[10000, 11]]

## `collections` count 

In [7]:
import collections

In [8]:
def majorityElement(nums):
    counts = collections.Counter(nums)
    return max(counts.keys(), key=counts.get)

In [9]:
majorityElement([1,3,3,3,5])

3

In [10]:
temp = collections.Counter([1,3,3,3,5])

In [1]:
import numpy as np

In [2]:
list(range(1,2))

[1]

#### list of lists

In [4]:
for i, j in [[3,5],[2,4]]:
    print(i,j)

3 5
2 4


### create heterogeneous lists

But this flexibility comes at a cost: to allow these flexible types, each item in the list must contain its own type info, reference count, and other information–that is, each item is a complete Python object. In the special case that all variables are of the same type, much of this information is redundant: it can be much more efficient to store data in a fixed-type array. 

In [2]:
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

### fixed type

In [6]:
x = np.array([range(i, i + 3) for i in [2, 4, 6]])
x

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

### numpy confusing functions

difference between `np.arrange` and `np.linspace`

In [9]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
np.linspace(0,18,10)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18.])

### numpy distributions

In [20]:
## uniform (a,b)
a = 3
b = 5
out = np.random.random(100) * (b-a) + a
np.quantile(out,[0,0.5,1])

array([3.00076968, 4.0011984 , 4.94693757])

In [33]:
## normal (mean, sd)
np.random.normal(loc = 0,scale=1,size=10)
np.random.normal(loc = 0,scale=1,size=(2,5))

array([[ 1.31970288, -0.3063791 , -2.06636449, -0.3009498 , -0.58731355],
       [-1.65031391, -1.11686232,  0.36602873, -0.98115691, -1.52107592]])

In [30]:
## multinomial like sample in R
np.random.choice(np.array(['a','b']),size=5,replace=True,p=[0.1,0.9])

array(['a', 'b', 'a', 'b', 'b'], dtype='<U1')

In [34]:
## sample random intergers from discrete 0 to 9
np.random.randint(0, 10, (3, 3))

9

In [3]:
from datetime import date

class Student:
    def __init__(self, name, age):
        self.name = name
        self.age = age

    @classmethod
    def calculate_age(cls, name, birth_year):
        # calculate age an set it as a age
        # return new object
        return cls(name, date.today().year - birth_year)

    def show(self):
        print(self.name + "'s age is: " + str(self.age))

jessa = Student('Jessa', 20)
jessa.show()

# create new object using the factory method
joy = Student.calculate_age("Joy", 1995)
joy.show()

Jessa's age is: 20
Joy's age is: 27


### dictionary

In [4]:
hashmap = {}
hashmap[35] = 1
hashmap[26] = 2

In [5]:
hashmap

{35: 1, 26: 2}

In [6]:
35 in hashmap

True

In [10]:
[hashmap[35], hashmap[26]]

[1, 2]

In [12]:
min(hashmap[35], hashmap[26])

1

In [18]:
list(reversed(range(5)))

[4, 3, 2, 1, 0]

### heap
To access the smallest item without popping it, use `heap[0]`.

In [13]:
# Python code to demonstrate working of 
# heapify(), heappush() and heappop()
  
# importing "heapq" to implement heap queue
import heapq
  
# initializing list
li = [5, 7, 9, 1, 3]
  
# using heapify to convert list into heap
heapq.heapify(li)
  
# printing created heap
print ("The created heap is : ",end="")
print (list(li))
  
# using heappush() to push elements into heap
# pushes 4
heapq.heappush(li,4)
  
# printing modified heap
print ("The modified heap after push is : ",end="")
print (list(li))
  
# using heappop() to pop smallest element
print ("The popped and smallest element is : ",end="")
print (heapq.heappop(li))

The created heap is : [1, 3, 9, 7, 5]
The modified heap after push is : [1, 3, 4, 7, 5, 9]
The popped and smallest element is : 1


In [3]:
for i, j in [[3,5],[2,4]]:
    print(i,j)

3 5
2 4


## Parsing numbers from text

In [6]:
txt = "h3110 23 cat 444.4 rabbit 11 2 dog"
[s for s in txt.split(" ") if s.isnumeric()]
#[23, 11, 2]

['23', '11', '2']

In [25]:
l = []
for t in txt.split():
    try:
        l.append(float(t))
    except ValueError:
        pass

## List Index

In [19]:
temp = [3,5,10,"kobe",5]

In [20]:
temp.index('kobe')

3

In [22]:
temp.index(5) ## find the index of first 5

1

In [24]:
temp.index(5,2) ##find 5 from index 2 to last

4

In [23]:
[i for i, x in enumerate(temp) if x == 5] 

[1, 4]

## List of list looping


In [1]:
temp = [[2,3],[5,10],[2,10]]
for i,j in temp:
    print(i,j)

2 3
5 10
2 10


## string operation `split` and `strip`

In [24]:
txt = "a \tb\tc\td\te"
things = txt.split("\t")
[x.strip(" ") for x in things]

['a', 'b', 'c', 'd', 'e']

## `copy` and `deepcopy`

In [16]:
import copy

In [17]:
temp = [3,2,[2,5]]
temp2 = temp.copy()
temp2[2][0]=1000
temp

[3, 2, [1000, 5]]

In [18]:
import copy
temp = [3,2,[2,5]]
temp2 = copy.copy(temp)
temp2[2][0]=1000
temp

[3, 2, [1000, 5]]

In [19]:
import copy
temp = [3,2,[2,5]]
temp2 = copy.deepcopy(temp)
temp2[2][0]=1000
temp

[3, 2, [2, 5]]

In [4]:
str(234)

'234'

### check whether a value (string or non-string) is `int` or `float`

`isinstance` work for both negative and postive

In [4]:
isinstance(1, int)

True

In [5]:
isinstance(-1, int)

True

In [2]:
isinstance("1", float)

False

In [7]:
isinstance(1.0, float)

True

In [15]:
"as".isnumeric()

False

`is_digit` works for non-negative number

In [20]:
"-3".isdigit()

False

In [8]:
"3".isdigit()

True

In [11]:
"0".isdigit()

True

## sort list of string by length

In [2]:
x = ["flower","flow","flight"]
sorted(x,key = lambda x: len(x))

['flow', 'flower', 'flight']

In [ ]:
for t in txt.split():
    try:
        l.append(float(t))
    except ValueError:
        pass

In [10]:
temp = ['5 min','-5 asdf','asdf','0 asdf']

In [11]:
out = []
for i in range(len(temp)):
    for j in temp[i].split():
        try:
            out.append(float(j))
        except ValueError:
            pass

In [12]:
out

[5.0, -5.0, 0.0]