## Resources
[Python-cheat-sheet](https://leetcode.com/discuss/study-guide/2122306/python-cheat-sheet-for-leetcode)

## Get the maximum key or value from dictionary

In [20]:
10*15*4*31*6*7*2

1562400

In [1]:
import numpy as np

In [19]:
np.arange(0.4, 1.1, 0.1)

array([0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [18]:
np.linspace(0.5, 1, 6)

array([0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [12]:
np.linspace(0.5,1, ste)

array([0.5       , 0.5122449 , 0.5244898 , 0.53673469, 0.54897959,
       0.56122449, 0.57346939, 0.58571429, 0.59795918, 0.61020408,
       0.62244898, 0.63469388, 0.64693878, 0.65918367, 0.67142857,
       0.68367347, 0.69591837, 0.70816327, 0.72040816, 0.73265306,
       0.74489796, 0.75714286, 0.76938776, 0.78163265, 0.79387755,
       0.80612245, 0.81836735, 0.83061224, 0.84285714, 0.85510204,
       0.86734694, 0.87959184, 0.89183673, 0.90408163, 0.91632653,
       0.92857143, 0.94081633, 0.95306122, 0.96530612, 0.97755102,
       0.98979592, 1.00204082, 1.01428571, 1.02653061, 1.03877551,
       1.05102041, 1.06326531, 1.0755102 , 1.0877551 , 1.1       ])

In [1]:
a_dictionary = {"a": 1, "b": 2, "c": 0}
b_dictionary = {"d": 1, "e": 2, "f": 0}

In [2]:
a_dictionary.update(b_dictionary)

In [5]:
a2_dict = {"a":1000}
a_dictionary.update(a2_dict)
a_dictionary

{'a': 1000, 'b': 2, 'c': 0, 'd': 1, 'e': 2, 'f': 0}

#### max elements

In [34]:
max(a_dictionary.keys(), key=a_dictionary.get)

'b'

In [28]:
max(a_dictionary, key=a_dictionary.get)

'b'

In [33]:
sorted(a_dictionary, key=a_dictionary.get)[-1]

'b'

In [36]:
sorted(a_dictionary, key=a_dictionary.get, reverse = True)[0]

'b'

#### max values

In [35]:
all_values = a_dictionary.values()
max(all_values)

2

__Sort dictionary with lexicographical order and descending counts__

In [26]:
count_dict = {"x":3,"y":4,"z":5,"a":4}

dict(sorted(count_dict.items(), key = lambda x: (-x[1],x[0]))).keys()

dict_keys(['z', 'a', 'y', 'x'])

__sort on both element ascending__

In [23]:
temp = [[5,6],[5,5],[2,10],[2,11]]

In [17]:
temp.sort()
temp

[[2, 10], [2, 11], [5, 5], [5, 6]]

__only sort the first element__

In [20]:
temp = [[5,6],[5,5],[2,10],[2,11]]
sorted(temp, key = lambda x:(x[0]))

[[2, 10], [2, 11], [5, 6], [5, 5]]

__sort on both (same as `.sort()`)__

In [21]:
sorted(temp, key = lambda x:(x[0],x[1])) 

[[2, 10], [2, 11], [5, 5], [5, 6]]

__sort on first ascending and second descending__

In [22]:
sorted(temp, key = lambda x:(x[0],-x[1])) 

[[2, 11], [2, 10], [5, 6], [5, 5]]

In [30]:
temp2 = {1:None}

In [17]:
1 in temp2

True

In [13]:
a = [3,5,1]
sorted(a)

[1, 3, 5]

In [11]:
sorted(a)

[1, 3, 5]

In [14]:
a.pop(0)
a

[5, 1]

In [41]:
intervals =  [[0,30],[5,10],[15,20]]
intervals = sorted(intervals,key = lambda x: (x[0],x[1]))
i = 0
intervals

[[0, 30], [5, 10], [15, 20]]

In [40]:
if (intervals[i][1]>intervals[i+1][0]) or (intervals[i][0] == intervals[i+1][0]):
    print("false") 

false


In [43]:
len(intervals)

3

In [25]:
temp = [[5,6],[5,5],[2,10],[2,11]]
temp.pop()
temp

[[5, 6], [5, 5], [2, 10]]

In [27]:
temp = [[5,6],[5,5],[2,10],[2,11]]
temp.pop(0)
temp

[[5, 5], [2, 10], [2, 11]]

In [30]:
temp = [[5,6],[5,5],[2,10],[2,11]]
for i in range(len(temp)-1):
    temp.pop(0)

In [31]:
temp

[[2, 11]]

In [33]:
temp2 = temp[-1]

In [34]:
temp2[0] = 10000
temp

[[10000, 11]]

## `dictionary.get()`

In [21]:
a = {'x':3,'y':100}

In [22]:
a.get('x')

3

__`.get()` won't raise error__

In [23]:
a.get('z')

In [24]:
a['z']

KeyError: 'z'

## List insert

In [7]:
a = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
a[5:5] = range(10, 13)
a

[0, 1, 2, 3, 4, 10, 11, 12, 5, 6, 7, 8, 9]

In [8]:
a.insert(0,1000)
a

[1000, 0, 1, 2, 3, 4, 10, 11, 12, 5, 6, 7, 8, 9]

## `collections` count 

In [7]:
import collections

In [8]:
def majorityElement(nums):
    counts = collections.Counter(nums)
    return max(counts.keys(), key=counts.get)

In [9]:
majorityElement([1,3,3,3,5])

3

In [10]:
temp = collections.Counter([1,3,3,3,5])

In [1]:
import numpy as np

In [2]:
list(range(1,2))

[1]

#### list of lists

In [4]:
for i, j in [[3,5],[2,4]]:
    print(i,j)

3 5
2 4


### create heterogeneous lists

But this flexibility comes at a cost: to allow these flexible types, each item in the list must contain its own type info, reference count, and other information–that is, each item is a complete Python object. In the special case that all variables are of the same type, much of this information is redundant: it can be much more efficient to store data in a fixed-type array. 

In [2]:
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

### fixed type

In [6]:
x = np.array([range(i, i + 3) for i in [2, 4, 6]])
x

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

### numpy confusing functions

difference between `np.arrange` and `np.linspace`

In [9]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
np.linspace(0,18,10)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18.])

### numpy distributions

In [20]:
## uniform (a,b)
a = 3
b = 5
out = np.random.random(100) * (b-a) + a
np.quantile(out,[0,0.5,1])

array([3.00076968, 4.0011984 , 4.94693757])

In [33]:
## normal (mean, sd)
np.random.normal(loc = 0,scale=1,size=10)
np.random.normal(loc = 0,scale=1,size=(2,5))

array([[ 1.31970288, -0.3063791 , -2.06636449, -0.3009498 , -0.58731355],
       [-1.65031391, -1.11686232,  0.36602873, -0.98115691, -1.52107592]])

In [30]:
## multinomial like sample in R
np.random.choice(np.array(['a','b']),size=5,replace=True,p=[0.1,0.9])

array(['a', 'b', 'a', 'b', 'b'], dtype='<U1')

In [34]:
## sample random intergers from discrete 0 to 9
np.random.randint(0, 10, (3, 3))

9

### dictionary

In [4]:
hashmap = {}
hashmap[35] = 1
hashmap[26] = 2

In [5]:
hashmap

{35: 1, 26: 2}

In [6]:
35 in hashmap

True

In [10]:
[hashmap[35], hashmap[26]]

[1, 2]

In [12]:
min(hashmap[35], hashmap[26])

1

In [18]:
list(reversed(range(5)))

[4, 3, 2, 1, 0]

### heap
To access the smallest item without popping it, use `heap[0]`.

In [13]:
# Python code to demonstrate working of 
# heapify(), heappush() and heappop()
  
# importing "heapq" to implement heap queue
import heapq
  
# initializing list
li = [5, 7, 9, 1, 3]
  
# using heapify to convert list into heap
heapq.heapify(li)
  
# printing created heap
print ("The created heap is : ",end="")
print (list(li))
  
# using heappush() to push elements into heap
# pushes 4
heapq.heappush(li,4)
  
# printing modified heap
print ("The modified heap after push is : ",end="")
print (list(li))
  
# using heappop() to pop smallest element
print ("The popped and smallest element is : ",end="")
print (heapq.heappop(li))

The created heap is : [1, 3, 9, 7, 5]
The modified heap after push is : [1, 3, 4, 7, 5, 9]
The popped and smallest element is : 1


In [3]:
for i, j in [[3,5],[2,4]]:
    print(i,j)

3 5
2 4


## Parsing numbers from text

In [6]:
txt = "h3110 23 cat 444.4 rabbit 11 2 dog"
[s for s in txt.split(" ") if s.isnumeric()]
#[23, 11, 2]

['23', '11', '2']

In [25]:
l = []
for t in txt.split():
    try:
        l.append(float(t))
    except ValueError:
        pass

## List Index

In [19]:
temp = [3,5,10,"kobe",5]

In [20]:
temp.index('kobe')

3

In [22]:
temp.index(5) ## find the index of first 5

1

In [24]:
temp.index(5,2) ##find 5 from index 2 to last

4

In [23]:
[i for i, x in enumerate(temp) if x == 5] 

[1, 4]

## List of list looping


In [1]:
temp = [[2,3],[5,10],[2,10]]
for i,j in temp:
    print(i,j)

2 3
5 10
2 10


## string operation `split` and `strip`

In [24]:
txt = "a \tb\tc\td\te"
things = txt.split("\t")
[x.strip(" ") for x in things]

['a', 'b', 'c', 'd', 'e']

## `copy` and `deepcopy`

In [16]:
import copy

In [17]:
temp = [3,2,[2,5]]
temp2 = temp.copy()
temp2[2][0]=1000
temp

[3, 2, [1000, 5]]

In [18]:
import copy
temp = [3,2,[2,5]]
temp2 = copy.copy(temp)
temp2[2][0]=1000
temp

[3, 2, [1000, 5]]

In [19]:
import copy
temp = [3,2,[2,5]]
temp2 = copy.deepcopy(temp)
temp2[2][0]=1000
temp

[3, 2, [2, 5]]

In [4]:
str(234)

'234'

### check whether a value (string or non-string) is `int` or `float`

`isinstance` work for both negative and postive

In [4]:
isinstance(1, int)

True

In [5]:
isinstance(-1, int)

True

In [2]:
isinstance("1", float)

False

In [7]:
isinstance(1.0, float)

True

In [15]:
"as".isnumeric()

False

`is_digit` works for non-negative number

In [20]:
"-3".isdigit()

False

In [8]:
"3".isdigit()

True

In [11]:
"0".isdigit()

True

## sort list of string by length

In [2]:
x = ["flower","flow","flight"]
sorted(x,key = lambda x: len(x))

['flow', 'flower', 'flight']

In [ ]:
for t in txt.split():
    try:
        l.append(float(t))
    except ValueError:
        pass

In [10]:
temp = ['5 min','-5 asdf','asdf','0 asdf']

In [11]:
out = []
for i in range(len(temp)):
    for j in temp[i].split():
        try:
            out.append(float(j))
        except ValueError:
            pass

In [12]:
out

[5.0, -5.0, 0.0]

### The `isalnum()` method returns True if all characters in the string are alphanumeric (either alphabets or numbers).

In [2]:
name1 = "Python3"
name1.isalnum()

True

In [4]:
"asdf :".isalnum()

False

In [5]:
":".isalnum()

False

In [6]:
if ":".isalnum():
    print('kobe')
else:
    print('bryant')

bryant


In [9]:
name1.lower()

'python3'

## `zip` transpose
`zip(*a)` is equal to `zip(a[0], a[1], a[2])`.

In [ ]:
mat = [[0,0,1,0],[0,0,0,0],[0,0,0,0],[0,1,0,0]]

In [26]:
np.array(mat_t)

array([[0, 0, 0, 0],
       [0, 0, 0, 1],
       [1, 0, 0, 0],
       [0, 0, 0, 0]])

In [38]:
list(zip(*mat))

[(0, 0, 0, 0), (0, 0, 0, 1), (1, 0, 0, 0), (0, 0, 0, 0)]

## `pop` also works as below

In [1]:
temp = [3,2,5]
temp2 = [3,2,5]
temp2[temp.pop(1)]

5