## Novelty detection review
[referece](https://scikit-learn.org/stable/modules/outlier_detection.html#isolation-forest)

In [70]:
from sklearn.svm import OneClassSVM
from sklearn.ensemble import IsolationForest
from sklearn.neighbors import LocalOutlierFactor
from sklearn.covariance import EllipticEnvelope
import numpy as np
import pandas as pd

In [60]:
rng = np.random.RandomState(0)
x = rng.normal(size = (1000,1))
x_to_test = rng.uniform(size = (10,1),low = -5, high =5)

In [61]:
x_to_test

array([[ 3.21903908],
       [ 2.00528623],
       [ 3.83077597],
       [ 4.66575107],
       [ 2.74747614],
       [ 4.94233083],
       [ 1.14769886],
       [-4.62870396],
       [-4.85748485],
       [-1.57896125]])

In [73]:
model = OneClassSVM(gamma = 'auto', nu =0.1).fit(x) ## sensitive to nu parameter
model.predict(x_to_test)

array([-1, -1, -1, -1, -1, -1,  1, -1, -1,  1], dtype=int64)

In [63]:
model2 = IsolationForest(n_estimators=20, warm_start=False,random_state=8888)
model2.fit(x).predict(x_to_test)

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1])

In [64]:
# add 10 more trees  
model2.set_params(n_estimators=20)
model2.fit(x).predict(x_to_test)

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1])

In [71]:
model3 = LocalOutlierFactor(n_neighbors = 10, novelty= True, contamination=0.0000001)
model3.fit(x).predict(x_to_test)

array([-1,  1, -1, -1,  1, -1,  1, -1, -1,  1])

In [72]:
model4 = EllipticEnvelope(contamination=0.0000001)
model4.fit(x).predict(x_to_test)

array([-1,  1, -1, -1,  1, -1,  1, -1, -1,  1])